#!/usr/bin/env python3
"""Final AI4Quality clinical dashboard.

This Streamlit app is intentionally read-only from the clinical point of view: it
loads the consolidated SQLite database produced by _04_Recommendations and shows
only recommendations that were already generated by the offline LLM batch job.
That design keeps the dashboard responsive during clinical review.
"""
from __future__ import annotations

import json
import sqlite3
import sys
from pathlib import Path
from typing import Iterable

import pandas as pd
import streamlit as st


APP_DIR = Path(__file__).resolve().parent
ROOT = APP_DIR.parent
RECOMMENDATIONS_DIR = ROOT / "_04_Recommendations"

# The recommendation modules are scripts rather than installed packages. Adding
# their folder to sys.path lets us reuse the existing database builder without
# duplicating the ingestion rules for QC, RCA, injector data, and warnings.
if str(RECOMMENDATIONS_DIR) not in sys.path:
    sys.path.insert(0, str(RECOMMENDATIONS_DIR))

try:
    from build_database import DB_PATH, build_database
except ModuleNotFoundError as exc:  # pragma: no cover - shown in Streamlit UI
    st.error(f"Missing module: {exc.name}. Run the dashboard from the correct AI4Quality environment.")
    st.stop()


STATUS_LABELS = {
    "optimal": "Optimal",
    "acceptable": "Acceptable",
    "acceptable_low": "Acceptable low",
    "acceptable_high": "Acceptable high",
    "warning_low": "Low warning",
    "warning_high": "High warning",
    "critical_low": "Critical low",
    "critical_high": "Critical high",
    "missing": "Missing",
}

STATUS_ORDER = {
    "critical_high": 0,
    "critical_low": 1,
    "warning_high": 2,
    "warning_low": 3,
    "missing": 4,
    "acceptable_low": 5,
    "acceptable_high": 5,
    "optimal": 6,
}

STATUS_COLORS = {
    "critical_high": "#f79009",
    "critical_low": "#d92d20",
    "warning_high": "#b54708",
    "warning_low": "#dc6803",
    "missing": "#667085",
    "acceptable_low": "#039855",
    "acceptable_high": "#039855",
    "optimal": "#027a48",
}

WARNING_LABELS = {
    "none": "No warning",
    "low": "Low warning",
    "medium": "Medium warning",
    "high": "High warning",
}
UNSPECIFIED_PROCEDURE = "Unspecified procedure"
UNSPECIFIED_PHASE = "Unspecified phase"
UNSPECIFIED_SCANNER = "Unspecified scanner"
NO_QC_STATUS = "No QC status"
NO_RCA_LABEL = "No RCA"


def _as_text(value: object, default: str = "") -> str:
    """Return a clean display string for values that may be NaN or None."""
    if value is None or pd.isna(value):
        return default
    text = str(value).strip()
    if text.lower() in {"", "nan", "none", "null"}:
        return default
    return text


def _sort_key(value: object) -> tuple[int, object]:
    """Sort numeric CT identifiers numerically and all other IDs alphabetically."""
    text = _as_text(value)
    return (0, int(text)) if text.isdigit() else (1, text)


def _read_json(value: object) -> dict:
    """Decode JSON stored in SQLite cells, returning an empty dict on bad input."""
    text = _as_text(value)
    if not text:
        return {}
    try:
        decoded = json.loads(text)
    except json.JSONDecodeError:
        return {}
    return decoded if isinstance(decoded, dict) else {}


def _quality_field(row: pd.Series, key: str, default: object = "") -> object:
    """Read a quality field from the normalized row or its persisted QC payload."""
    value = row.get(key)
    if value is not None and not (isinstance(value, float) and pd.isna(value)) and _as_text(value):
        return value
    return _read_json(row.get("qc_data_json")).get(key, default)


def _format_quality_number(value: object) -> str:
    if value is None or (isinstance(value, float) and pd.isna(value)) or _as_text(value) == "":
        return "n/a"
    try:
        return f"{float(value):.1f}"
    except (TypeError, ValueError):
        return _as_text(value, "n/a")


def _format_percentage(value: object) -> str:
    """Format a phase-prediction probability as a percentage."""
    if value is None or pd.isna(value):
        return "n/a"
    return f"{float(value) * 100.0:.1f}%"


def _phase_match_label(value: object) -> str:
    """Convert nullable dataframe booleans into a display label."""
    if value is None or (not isinstance(value, str) and pd.isna(value)):
        return "No prediction"
    return "Match" if bool(value) else "Mismatch"


def _normalize_phase_name(value: object) -> str:
    """Normalize phase labels before comparing stored and predicted phases."""
    return _as_text(value).lower().replace(" ", "_")


def _phase_prediction_matches(actual: str, predicted: str) -> bool:
    """Compare Italian stored phase labels with the model's English labels."""
    if not actual or not predicted:
        return False
    if actual == predicted:
        return True
    return (actual == "venosa" and "venous" in predicted) or (actual == "arteriosa" and "arterial" in predicted)


def _effective_phase(row: pd.Series) -> str:
    """Resolve the true phase using the same rule as quality-check evaluation."""
    phase = _normalize_phase_name(row.get("phase_name"))
    metadata = _read_json(row.get("series_data_json"))
    ct_type = _normalize_phase_name(metadata.get("CT_type"))
    if not phase and ct_type == "vascular":
        return "arteriosa"
    return phase


def _phase_prediction_map(data: dict[str, pd.DataFrame]) -> dict[tuple[str, str], dict[str, object]]:
    """Load phase predictions from QC artifact metadata for each series."""
    predictions: dict[tuple[str, str], dict[str, object]] = {}
    for _, row in data["image_quality"].iterrows():
        key = (str(row.get("ct_id")), _as_text(row.get("series_folder")))
        series_dir = _read_json(row.get("qc_data_json")).get("series_dir")
        phase_path = _resolve_artifact_path(series_dir)
        if phase_path is None:
            data_root = ROOT.parent / "DATA"
            ct_prefix = f"CT_QUALITY_{key[0]}_"
            series_name = key[1].lower()
            search_roots = [data_root / "CDI_NEXO_072026" / "2_nii", data_root]
            candidates = []
            for search_root in search_roots:
                candidates.extend(
                    path for path in search_root.glob(f"{ct_prefix}*/**/phase.json")
                    if series_name in path.parent.name.lower()
                )
                if candidates:
                    break
            if candidates:
                phase_path = candidates[0].parent
        if phase_path is None:
            continue
        phase_file = phase_path / "phase.json"
        if not phase_file.exists():
            continue
        try:
            with phase_file.open("r", encoding="utf-8") as stream:
                prediction = json.load(stream)
        except (OSError, json.JSONDecodeError):
            continue
        if isinstance(prediction, dict) and prediction.get("phase"):
            predictions[key] = prediction
    return predictions


def _join_unique(values: Iterable[object], fallback: str = "-") -> str:
    """Compact a column into a comma-separated list without repeated labels."""
    clean_values = sorted({_as_text(value) for value in values if _as_text(value)})
    return ", ".join(clean_values) if clean_values else fallback


def _worst_status(values: Iterable[object]) -> str:
    """Return the clinically most relevant QC status in a group of ROI rows."""
    statuses = [_as_text(value) for value in values if _as_text(value)]
    if not statuses:
        return "missing"
    return sorted(statuses, key=lambda status: STATUS_ORDER.get(status, 99))[0]


def _split_pipe(value: object) -> list[str]:
    """Split RCA pipe-separated recommendation fields into readable bullets."""
    text = _as_text(value)
    if not text:
        return []
    return [item.strip() for item in text.split(" | ") if item.strip()]


def _resolve_artifact_path(path_value: object) -> Path | None:
    """Resolve stored relative or absolute artifact paths to existing files."""
    text = _as_text(path_value)
    if not text:
        return None
    path = Path(text)
    if not path.is_absolute():
        path = ROOT / path
    return path if path.exists() else None


def _image_paths_from_quality_rows(quality_rows: pd.DataFrame) -> list[Path]:
    """Collect segmentation/QC overlay images saved by the quality-check step."""
    paths: list[Path] = []
    seen: set[Path] = set()
    for _, row in quality_rows.iterrows():
        candidates = [row.get("output_image_path"), row.get("image_path")]
        candidates.extend(_read_json(row.get("qc_data_json")).get(key) for key in ("output_image_path", "image_path"))
        for candidate in candidates:
            path = _resolve_artifact_path(candidate)
            if path is not None and path not in seen:
                seen.add(path)
                paths.append(path)
    return paths


def _configure_page() -> None:
    """Apply Streamlit page settings and restrained clinical styling."""
    st.set_page_config(page_title="AI4Quality Clinical Review", layout="wide")
    st.markdown(
        """
        <style>
        :root {
            --aq-ink: #1d2939;
            --aq-muted: #667085;
            --aq-line: #d0d5dd;
            --aq-panel: #f9fafb;
            --aq-soft-blue: #eef6ff;
            --aq-blue: #175cd3;
            --aq-red: #b42318;
            --aq-green: #027a48;
        }
        .stApp { background: linear-gradient(180deg, #f7faff 0%, #ffffff 42%); }
        .block-container { padding-top: 2.15rem; max-width: 1540px; }
        h1, h2, h3 { color: var(--aq-ink); letter-spacing: 0; }
        h2 { margin-top: 0.35rem; }
        .aq-app-title {
            align-items: baseline;
            display: flex;
            gap: 0.75rem;
            margin: 0 0 0.75rem 0;
        }
        .aq-app-title h1 {
            font-size: 1.75rem;
            line-height: 1;
            margin: 0;
        }
        .aq-app-title span {
            color: var(--aq-muted);
            font-size: 0.9rem;
            font-weight: 700;
        }
        div[data-testid="stMetric"] {
            background: #ffffff;
            border: 1px solid var(--aq-line);
            border-radius: 8px;
            min-height: 82px;
            padding: 0.72rem 0.9rem;
            box-shadow: 0 8px 24px rgba(16, 24, 40, 0.04);
        }
        div[data-testid="stMetricLabel"] { white-space: normal; }
        div[data-testid="stMetricValue"] { font-size: 1.65rem; line-height: 1.15; }
        .aq-hero {
            border: 1px solid var(--aq-line);
            border-radius: 8px;
            padding: 0.95rem 1.05rem;
            background: linear-gradient(135deg, #ffffff 0%, var(--aq-soft-blue) 100%);
            margin-bottom: 0.7rem;
            box-shadow: 0 14px 40px rgba(16, 24, 40, 0.06);
        }
        .aq-hero h1 {
            font-size: clamp(1.65rem, 2.4vw, 2.35rem);
            line-height: 1.12;
            margin: 0.12rem 0 0.45rem 0;
        }
        .aq-muted { color: var(--aq-muted); }
        .aq-card {
            border: 1px solid var(--aq-line);
            border-radius: 8px;
            padding: 0.95rem 1rem;
            background: #ffffff;
            margin-bottom: 0.75rem;
            box-shadow: 0 8px 24px rgba(16, 24, 40, 0.035);
        }
        .aq-card-title { font-weight: 800; color: var(--aq-ink); margin-bottom: 0.25rem; }
        .aq-phase-comparison {
            background: #f8fafc;
            border: 1px solid var(--aq-line);
            border-radius: 6px;
            color: var(--aq-ink);
            margin-top: 0.65rem;
            padding: 0.65rem 0.75rem;
        }
        .aq-phase-line { margin: 0.15rem 0; }
        .aq-phase-badge {
            border-radius: 999px;
            display: inline-block;
            font-size: 0.78rem;
            font-weight: 800;
            margin-left: 0.4rem;
            padding: 0.1rem 0.45rem;
        }
        .aq-phase-match { background: #dcfce7; color: #166534; }
        .aq-phase-mismatch { background: #fee2e2; color: #991b1b; }
        .aq-attenuation {
            background: #f3f4f6;
            border-left: 4px solid #0369a1;
            color: #1e293b;
            margin-top: 0.75rem;
            padding: 0.65rem 0.75rem;
        }
        .aq-roi-warning {
            color: #991b1b;
            margin-top: 0.55rem;
        }
        .aq-section-label {
            color: var(--aq-muted);
            font-size: 0.76rem;
            font-weight: 800;
            letter-spacing: 0.06em;
            margin: 0.15rem 0 0.35rem 0;
            text-transform: uppercase;
        }
        .aq-status-row { display: flex; flex-wrap: wrap; gap: 0.45rem; margin: 0.8rem 0 1rem 0; }
        .aq-status-pill {
            display: inline-flex;
            align-items: center;
            gap: 0.35rem;
            border-radius: 999px;
            padding: 0.35rem 0.65rem;
            color: #ffffff;
            font-size: 0.83rem;
            font-weight: 800;
        }
        .aq-chip {
            display: inline-block;
            border-radius: 999px;
            padding: 0.18rem 0.55rem;
            font-size: 0.8rem;
            font-weight: 800;
            margin: 0.1rem 0.25rem 0.1rem 0;
            background: #eef4ff;
            color: var(--aq-blue);
        }
        .aq-alert {
            border-left: 5px solid var(--aq-red);
            background: #fff4f2;
            color: #7a271a;
            border-radius: 8px;
            padding: 0.72rem 0.95rem;
            margin-bottom: 0.7rem;
        }
        .aq-warning-low { border-left-color: #b54708; background: #fffaeb; color: #7a2e0e; }
        .aq-warning-medium { border-left-color: #dc6803; background: #fff7ed; color: #9a3412; }
        .aq-warning-high { border-left-color: #b42318; background: #fff1f3; color: #912018; }
        .aq-success {
            border-left: 5px solid var(--aq-green);
            background: #ecfdf3;
            color: #054f31;
            border-radius: 8px;
            padding: 0.72rem 0.95rem;
            margin-bottom: 0.7rem;
        }
        .aq-llm {
            border: 1px solid #b2ddff;
            border-left: 5px solid var(--aq-blue);
            background: #eff8ff;
            color: var(--aq-ink);
            border-radius: 8px;
            padding: 0.95rem 1rem;
            white-space: pre-wrap;
            max-height: 310px;
            overflow: auto;
        }
        .aq-image-panel {
            border: 1px solid var(--aq-line);
            border-radius: 8px;
            background: #ffffff;
            padding: 0.8rem 0.85rem;
            box-shadow: 0 18px 48px rgba(16, 24, 40, 0.09);
        }
        .aq-image-panel-title {
            align-items: center;
            display: flex;
            justify-content: space-between;
            gap: 1rem;
            margin-bottom: 0.55rem;
        }
        .aq-image-panel-title strong { color: var(--aq-ink); }
        .aq-image-caption {
            color: var(--aq-muted);
            font-size: 0.82rem;
            margin-top: 0.45rem;
            overflow-wrap: anywhere;
        }
        div[data-testid="stImage"] {
            border: 1px solid var(--aq-line);
            border-radius: 8px;
            background: #ffffff;
            padding: 0.5rem;
            box-shadow: 0 12px 32px rgba(16, 24, 40, 0.08);
        }
        div[data-testid="stImage"] img { border-radius: 6px; }
        </style>
        """,
        unsafe_allow_html=True,
    )


def _database_has_required_tables(path: Path) -> bool:
    """Check whether the SQLite file contains the tables this dashboard needs."""
    if not path.exists():
        return False
    try:
        with sqlite3.connect(path) as db:
            tables = {row[0] for row in db.execute("SELECT name FROM sqlite_master WHERE type='table'")}
            exam_columns = {row[1] for row in db.execute("PRAGMA table_info(exams)")} if "exams" in tables else set()
    except sqlite3.Error:
        return False
    required = {"series", "image_quality", "rca", "injector_data", "patient_warnings", "recommendations"}
    return required.issubset(tables) and "patient_name" not in exam_columns


@st.cache_data(show_spinner=False)
def _load_database(refresh_token: int, force_rebuild: bool, db_mtime_ns: int) -> dict[str, pd.DataFrame]:
    """Load the consolidated database, rebuilding source tables when necessary.

    The refresh_token argument is intentionally unused except as a Streamlit cache
    key. Incrementing it lets the sidebar Refresh button force a fresh read.
    """
    del refresh_token, db_mtime_ns

    if force_rebuild or not _database_has_required_tables(DB_PATH):
        build_database(DB_PATH)

    with sqlite3.connect(DB_PATH) as db:
        return {
            table: pd.read_sql_query(f"SELECT * FROM {table}", db)
            for table in ("exams", "series", "image_quality", "rca", "injector_data", "patient_warnings", "recommendations")
        }


def _series_summary(data: dict[str, pd.DataFrame]) -> pd.DataFrame:
    """Build one row per analyzed series with QC, RCA, and metadata labels."""
    series = data["series"].copy()
    quality = data["image_quality"].copy()
    rca = data["rca"].copy()
    phase_predictions = _phase_prediction_map(data)

    if series.empty and quality.empty:
        return pd.DataFrame()

    # QC is ROI-level; this aggregation gives clinicians the worst status and the
    # number of affected ROIs while keeping the detailed ROI rows expandable later.
    qc_summary = pd.DataFrame()
    if not quality.empty:
        qc_summary = quality.groupby(["ct_id", "series_folder"], dropna=False).agg(
            worst_status=("status", _worst_status),
            n_roi=("roi_name", "count"),
            n_critical=("status", lambda values: sum(_as_text(value).startswith("critical") for value in values)),
            n_missing=("status", lambda values: sum(_as_text(value) == "missing" for value in values)),
            affected_rois=("roi_name", _join_unique),
            metrics=("metric_name", _join_unique),
        ).reset_index()

    # RCA may have several schemas per series. Compact labels and schemas so the
    # table remains scan-friendly, then show the full rows in the detail panel.
    rca_summary = pd.DataFrame()
    if not rca.empty:
        rca_summary = rca.groupby(["ct_id", "series_folder"], dropna=False).agg(
            rca_labels=("rca_label", _join_unique),
            rca_schemas=("rca_schema", _join_unique),
            n_rca=("rca_schema", "count"),
        ).reset_index()

    keys = qc_summary[["ct_id", "series_folder"]].drop_duplicates() if not qc_summary.empty else pd.DataFrame()
    if keys.empty and not rca_summary.empty:
        keys = rca_summary[["ct_id", "series_folder"]].drop_duplicates()

    output = keys.merge(series, on=["ct_id", "series_folder"], how="left")
    if not qc_summary.empty:
        output = output.merge(qc_summary, on=["ct_id", "series_folder"], how="left")
    if not rca_summary.empty:
        output = output.merge(rca_summary, on=["ct_id", "series_folder"], how="left")

    for column in ("phase_name", "procedure_code", "scanner", "worst_status", "affected_rois", "metrics", "rca_labels", "rca_schemas"):
        if column not in output.columns:
            output[column] = ""
        output[column] = output[column].fillna("").astype(str)
    output["procedure_code"] = output["procedure_code"].replace("", UNSPECIFIED_PROCEDURE)
    output["phase_name"] = output["phase_name"].replace("", UNSPECIFIED_PHASE)
    output["scanner"] = output["scanner"].replace("", UNSPECIFIED_SCANNER)
    output["worst_status"] = output["worst_status"].replace("", NO_QC_STATUS)
    output["rca_labels"] = output["rca_labels"].replace({"": NO_RCA_LABEL, "-": NO_RCA_LABEL})
    output["n_roi"] = pd.to_numeric(output.get("n_roi", 0), errors="coerce").fillna(0).astype(int)
    output["n_critical"] = pd.to_numeric(output.get("n_critical", 0), errors="coerce").fillna(0).astype(int)
    output["n_missing"] = pd.to_numeric(output.get("n_missing", 0), errors="coerce").fillna(0).astype(int)
    output["n_rca"] = pd.to_numeric(output.get("n_rca", 0), errors="coerce").fillna(0).astype(int)
    output["actual_phase"] = output.apply(_effective_phase, axis=1)
    output["predicted_phase"] = [
        _as_text(phase_predictions.get((str(row.ct_id), str(row.series_folder)), {}).get("phase"))
        for row in output.itertuples(index=False)
    ]
    output["predicted_phase_probability"] = [
        phase_predictions.get((str(row.ct_id), str(row.series_folder)), {}).get("probability")
        for row in output.itertuples(index=False)
    ]
    output["phase_prediction_matches"] = [
        _phase_prediction_matches(_normalize_phase_name(actual), _normalize_phase_name(predicted))
        if predicted else pd.NA
        for actual, predicted in zip(output["actual_phase"], output["predicted_phase"], strict=False)
    ]
    output["phase_name"] = output["actual_phase"].replace("", UNSPECIFIED_PHASE)
    return output


def _patient_summary(series_summary: pd.DataFrame, data: dict[str, pd.DataFrame]) -> pd.DataFrame:
    """Build one row per patient for filtering, navigation, and top KPIs."""
    if series_summary.empty:
        return pd.DataFrame()

    patients = series_summary.groupby("ct_id", dropna=False).agg(
        n_series=("series_folder", "nunique"),
        n_critical_series=("worst_status", lambda values: sum(_as_text(value).startswith("critical") for value in values)),
        n_rca_series=("n_rca", lambda values: sum(int(value) > 0 for value in values)),
        n_missing_segmentations=("n_missing", lambda values: sum(int(value) > 0 for value in values)),
        procedures=("procedure_code", _join_unique),
        phases=("phase_name", _join_unique),
        scanners=("scanner", _join_unique),
    ).reset_index()

    warnings = data["patient_warnings"].copy()
    if warnings.empty:
        patients["warning_priority"] = "none"
        patients["warning"] = ""
        patients["segmentation_warning"] = ""
    else:
        patients = patients.merge(warnings, on="ct_id", how="left")
        patients["warning_priority"] = patients["warning_priority"].fillna("none").astype(str)
        for column in ("warning", "warning_evidence", "segmentation_warning", "segmentation_warning_evidence"):
            if column not in patients.columns:
                patients[column] = ""
            patients[column] = patients[column].fillna("").astype(str)

    recommendations = data["recommendations"].copy()
    if recommendations.empty:
        patients["has_recommendation"] = False
        patients["recommendation_created_at"] = ""
    else:
        current = recommendations[recommendations["scope"].fillna("").astype(str).eq("exam")].copy()
        current = current.sort_values("created_at").drop_duplicates("ct_id", keep="last")
        patients = patients.merge(current[["ct_id", "created_at"]], on="ct_id", how="left")
        patients["has_recommendation"] = patients["created_at"].notna()
        patients["recommendation_created_at"] = patients["created_at"].fillna("").astype(str)
        patients = patients.drop(columns=["created_at"], errors="ignore")

    patients["ct_folder"] = "CT_QUALITY_" + patients["ct_id"].astype(str)
    return patients.sort_values("ct_id", key=lambda column: column.map(_sort_key))


def _filter_data(series_summary: pd.DataFrame, patient_summary: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Render sidebar controls and return the filtered patient and series rows."""
    with st.sidebar:
        st.header("Filters")
        search = st.text_input("Search CT, procedure, or scanner", value="")
        procedure_options = sorted({_as_text(value) for value in series_summary["procedure_code"] if _as_text(value)})
        phase_options = sorted({_as_text(value) for value in series_summary["phase_name"] if _as_text(value)})
        scanner_options = sorted({_as_text(value) for value in series_summary["scanner"] if _as_text(value)})
        status_options = sorted({_as_text(value) for value in series_summary["worst_status"] if _as_text(value)}, key=lambda value: STATUS_ORDER.get(value, 99))
        rca_options = sorted({_as_text(label) for labels in series_summary["rca_labels"] for label in labels.split(", ") if _as_text(label)})
        warning_options = list(WARNING_LABELS.keys())

        procedures = st.multiselect("Procedure", procedure_options, default=procedure_options)
        phases = st.multiselect("Phase", phase_options, default=phase_options)
        scanners = st.multiselect("Scanner", scanner_options, default=scanner_options)
        statuses = st.multiselect("QC status", status_options, default=status_options, format_func=lambda value: STATUS_LABELS.get(value, value))
        rca_labels = st.multiselect("Root cause", rca_options, default=rca_options)
        warning_priorities = st.multiselect("Warning priority", warning_options, default=warning_options, format_func=lambda value: WARNING_LABELS.get(value, value))
        recommendation_state = st.radio("LLM report", ["All", "Generated", "Missing"], horizontal=False)

    filtered_series = series_summary.copy()
    if procedures:
        filtered_series = filtered_series[filtered_series["procedure_code"].isin(procedures)]
    if phases:
        filtered_series = filtered_series[filtered_series["phase_name"].isin(phases)]
    if scanners:
        filtered_series = filtered_series[filtered_series["scanner"].isin(scanners)]
    if statuses:
        filtered_series = filtered_series[filtered_series["worst_status"].isin(statuses)]
    if rca_labels:
        filtered_series = filtered_series[filtered_series["rca_labels"].apply(lambda text: any(label in str(text).split(", ") for label in rca_labels))]

    allowed_patient_ids = set(filtered_series["ct_id"].astype(str))
    filtered_patients = patient_summary[patient_summary["ct_id"].astype(str).isin(allowed_patient_ids)].copy()
    filtered_patients = filtered_patients[filtered_patients["warning_priority"].fillna("none").isin(warning_priorities)]
    if recommendation_state == "Generated":
        filtered_patients = filtered_patients[filtered_patients["has_recommendation"]]
    elif recommendation_state == "Missing":
        filtered_patients = filtered_patients[~filtered_patients["has_recommendation"]]

    if search.strip():
        needle = search.strip().lower()
        haystack = filtered_patients[["ct_id", "ct_folder", "procedures", "scanners", "phases"]].fillna("").agg(" ".join, axis=1).str.lower()
        filtered_patients = filtered_patients[haystack.str.contains(needle, regex=False)]

    allowed_patient_ids = set(filtered_patients["ct_id"].astype(str))
    filtered_series = filtered_series[filtered_series["ct_id"].astype(str).isin(allowed_patient_ids)]
    return filtered_patients, filtered_series


def _metric_row(filtered_patients: pd.DataFrame, filtered_series: pd.DataFrame) -> None:
    """Show cohort-level counters above the selected patient."""
    st.markdown(
        "<div class='aq-app-title'><h1>AI4Quality</h1><span>Clinical quality review</span></div>",
        unsafe_allow_html=True,
    )
    columns = st.columns(6)
    columns[0].metric("Number of patients", len(filtered_patients))
    columns[1].metric("Number of series", len(filtered_series))
    columns[2].metric("Number of critical patients", int((filtered_patients["n_critical_series"] > 0).sum()) if not filtered_patients.empty else 0)
    columns[3].metric("Number of critical series", int(filtered_series["worst_status"].str.startswith("critical").sum()) if not filtered_series.empty else 0)
    columns[4].metric("Number with RCA", int((filtered_patients["n_rca_series"] > 0).sum()) if not filtered_patients.empty else 0)
    columns[5].metric("Number of missing segmentations", int((filtered_patients["n_missing_segmentations"] > 0).sum()) if not filtered_patients.empty else 0)
    if not filtered_series.empty:
        counts = filtered_series["worst_status"].value_counts().to_dict()
        pills = []
        for status in sorted(counts, key=lambda value: STATUS_ORDER.get(value, 99)):
            color = STATUS_COLORS.get(status, "#667085")
            pills.append(
                f"<span class='aq-status-pill' style='background:{color};'>Number of {STATUS_LABELS.get(status, status).lower()}: {counts[status]}</span>"
            )
        st.markdown(f"<div class='aq-status-row'>{''.join(pills)}</div>", unsafe_allow_html=True)


def _patient_selector(filtered_patients: pd.DataFrame) -> str | None:
    """Render stable previous/next navigation plus a searchable patient selector."""
    if filtered_patients.empty:
        st.warning("No patients match the selected filters.")
        return None

    labels = [f"CT {row.ct_id} | {row.n_critical_series} critical series | {row.procedures}" for row in filtered_patients.itertuples(index=False)]
    if "final_dashboard_patient_index" not in st.session_state:
        st.session_state.final_dashboard_patient_index = 0
    st.session_state.final_dashboard_patient_index = max(0, min(st.session_state.final_dashboard_patient_index, len(labels) - 1))

    previous_col, selector_col, next_col = st.columns([0.8, 3.2, 0.8])
    if previous_col.button("Previous", width="stretch", disabled=st.session_state.final_dashboard_patient_index == 0):
        st.session_state.final_dashboard_patient_index -= 1
    selected_label = selector_col.selectbox("Patient", labels, index=st.session_state.final_dashboard_patient_index)
    st.session_state.final_dashboard_patient_index = labels.index(selected_label)
    if next_col.button("Next", width="stretch", disabled=st.session_state.final_dashboard_patient_index == len(labels) - 1):
        st.session_state.final_dashboard_patient_index += 1

    return str(filtered_patients.iloc[st.session_state.final_dashboard_patient_index]["ct_id"])


def _render_patient_header(patient_row: pd.Series) -> None:
    """Show the most important patient-level information in one compact panel."""
    recommendation_state = "LLM report available" if bool(patient_row.get("has_recommendation")) else "LLM report not generated yet"
    recommendation_class = "aq-success" if bool(patient_row.get("has_recommendation")) else "aq-alert"
    st.markdown(
        f"""
        <div class="aq-hero">
            <div class="aq-muted">Integrated clinical review</div>
            <h1>CT {patient_row.get('ct_id')}</h1>
            <span class="aq-chip">{patient_row.get('ct_folder')}</span>
            <span class="aq-chip">{patient_row.get('n_series', 0)} series</span>
            <span class="aq-chip">{patient_row.get('n_critical_series', 0)} critical</span>
            <span class="aq-chip">{patient_row.get('procedures', '-')}</span>
            <span class="aq-chip">{patient_row.get('scanners', '-')}</span>
        </div>
        <div class="{recommendation_class}"><strong>{recommendation_state}</strong></div>
        """,
        unsafe_allow_html=True,
    )


def _render_warnings(patient_row: pd.Series) -> None:
    """Render patient and segmentation warnings only when they carry content."""
    warning_priority = _as_text(patient_row.get("warning_priority"), "none")
    warning = _as_text(patient_row.get("warning"))
    warning_evidence = _as_text(patient_row.get("warning_evidence"))
    if warning_priority != "none" and warning:
        warning_class = f"aq-alert aq-warning-{warning_priority}"
        st.markdown(
            f"<div class='{warning_class}'><strong>{WARNING_LABELS.get(warning_priority, warning_priority)}:</strong> {warning}<br><span class='aq-muted'>{warning_evidence}</span></div>",
            unsafe_allow_html=True,
        )

    segmentation_warning = _as_text(patient_row.get("segmentation_warning"))
    segmentation_evidence = _as_text(patient_row.get("segmentation_warning_evidence"))
    if segmentation_warning:
        st.markdown(
            f"<div class='aq-alert'><strong>Segmentation:</strong> {segmentation_warning}<br><span class='aq-muted'>{segmentation_evidence}</span></div>",
            unsafe_allow_html=True,
        )


def _has_current_missing_weight_rca(data: dict[str, pd.DataFrame], ct_id: str) -> bool:
    """Return whether the current RCA data contains the missing-weight dose outcome."""
    rca = data["rca"]
    if rca.empty:
        return False
    rows = rca[
        rca["ct_id"].astype(str).eq(str(ct_id))
        & rca["rca_schema"].fillna("").astype(str).eq("dose_schema_v1")
    ]
    return rows["rca_label"].fillna("").astype(str).str.lower().eq("missing weight").any()


def _latest_recommendation(data: dict[str, pd.DataFrame], ct_id: str) -> tuple[pd.Series | None, bool]:
    """Return the latest persisted exam-level LLM recommendation and stale-state flag."""
    recommendations = data["recommendations"]
    if recommendations.empty:
        return None, False
    rows = recommendations[
        recommendations["ct_id"].astype(str).eq(str(ct_id))
        & recommendations["scope"].fillna("").astype(str).eq("exam")
    ].sort_values("created_at")
    if rows.empty:
        return None, False
    latest = rows.iloc[-1]
    input_json = _as_text(latest.get("input_json"))
    input_text = input_json.lower()
    has_missing_weight_input = "missing weight" in input_text or "patient weight missing" in input_text
    stale_missing_weight = _has_current_missing_weight_rca(data, ct_id) and not has_missing_weight_input
    return latest, stale_missing_weight


def _render_recommendation(data: dict[str, pd.DataFrame], ct_id: str) -> None:
    """Show the stored LLM report; never invoke an LLM from the dashboard."""
    recommendation, stale = _latest_recommendation(data, ct_id)
    st.subheader("Clinical summary")
    if recommendation is None:
        st.info(
            "The LLM report is not available for this patient yet. "
            "Generate it in the background with: python _04_Recommendations/generate_recommendations.py"
        )
        return
    if stale:
        st.warning(
            "The stored LLM report was generated before the current missing-weight dose logic. "
            "Regenerate recommendations in the background before using this narrative summary."
        )
        return

    source = _as_text(recommendation.get("source"), "stored")
    created_at = _as_text(recommendation.get("created_at"), "date unavailable")
    st.caption(f"Source: {source} | Generated: {created_at}")
    st.markdown(f"<div class='aq-llm'>{_as_text(recommendation.get('recommendation'))}</div>", unsafe_allow_html=True)


def _render_series_table(patient_series: pd.DataFrame) -> None:
    """Show a compact, sortable table of the selected patient's analyzed series."""
    display = patient_series.copy()
    display["qc_status"] = display["worst_status"].map(lambda value: STATUS_LABELS.get(value, value))
    display["phase_prediction_matches"] = display["phase_prediction_matches"].map(_phase_match_label)
    columns = ["series_folder", "actual_phase", "predicted_phase", "phase_prediction_matches", "procedure_code", "scanner", "qc_status", "affected_rois", "rca_labels"]
    display = display[[column for column in columns if column in display.columns]].rename(columns={
        "series_folder": "Series",
        "actual_phase": "Actual phase",
        "predicted_phase": "Predicted phase",
        "phase_prediction_matches": "Phase match",
        "procedure_code": "Procedure",
        "scanner": "Scanner",
        "qc_status": "QC status",
        "affected_rois": "Affected ROIs",
        "rca_labels": "Root causes",
    })
    st.dataframe(display, hide_index=True, width="stretch")


def _render_roi_cards(quality_rows: pd.DataFrame) -> None:
    """Render ROI-level QC findings as compact cards for rapid clinical scanning."""
    if quality_rows.empty:
        st.info("No QC detail is available for this series.")
        return

    for _, row in quality_rows.sort_values(["status", "roi_name"], key=lambda column: column.map(lambda value: STATUS_ORDER.get(value, 99) if column.name == "status" else str(value))).iterrows():
        status = _as_text(row.get("status"), "missing")
        color = STATUS_COLORS.get(status, "#667085")
        value_label = _format_quality_number(_quality_field(row, "evaluated_value"))
        mean_label = f"{_format_quality_number(_quality_field(row, 'mean_hu'))} +/- {_format_quality_number(_quality_field(row, 'std_hu'))}"
        median_label = f"{_format_quality_number(_quality_field(row, 'median_hu'))} +/- {_format_quality_number(_quality_field(row, 'median_std_hu'))}"
        threshold_label = ""
        threshold_min_opt = _quality_field(row, "threshold_min_opt")
        if _as_text(threshold_min_opt):
            threshold_label = (
                f"<div><strong>Optimal:</strong> {_format_quality_number(threshold_min_opt)} to "
                f"{_format_quality_number(_quality_field(row, 'threshold_max_opt'))}</div>"
                f"<div><strong>Tolerance:</strong> {_format_quality_number(_quality_field(row, 'threshold_min_with_threshold'))} to "
                f"{_format_quality_number(_quality_field(row, 'threshold_max_with_threshold'))}</div>"
            )
        warning = _as_text(_quality_field(row, "warning"))
        warning_html = f"<div class='aq-roi-warning'><strong>Warning:</strong> {warning}</div>" if warning else ""
        attenuation_message = _as_text(_quality_field(row, "attenuation_message"))
        attenuation_html = ""
        if attenuation_message:
            consistency = _as_text(_quality_field(row, "attenuation_consistency"))
            consistency_color = "#b91c1c" if consistency == "incoherent" else "#0369a1"
            edge_count = _quality_field(row, "edge_slice_count")
            slice_label = f"first/last {int(float(edge_count))} vessel slices" if _as_text(edge_count) else "vessel endpoints"
            attenuation_html = (
                f"<div class='aq-attenuation' style='border-left-color:{consistency_color};'>"
                f"<strong>Attenuation consistency ({slice_label}):</strong><br>{attenuation_message}</div>"
            )
        st.markdown(
            f"""
            <div class="aq-card" style="border-left:5px solid {color};">
                <div class="aq-card-title">{_as_text(row.get('roi_name'), 'ROI')} - {STATUS_LABELS.get(status, status)}</div>
                <div class="aq-muted">{_as_text(row.get('metric_name'), 'metric')} | value: <strong>{value_label}</strong></div>
                <div><strong>Mean HU:</strong> {mean_label}</div>
                <div><strong>Median HU:</strong> {median_label}</div>
                {threshold_label}
                {attenuation_html}
                {warning_html}
            </div>
            """,
            unsafe_allow_html=True,
        )


def _render_rca_cards(rca_rows: pd.DataFrame) -> None:
    """Render RCA diagnoses with the explanation and protocol suggestions."""
    if rca_rows.empty:
        st.info("No root cause analysis is available for this series.")
        return

    for _, row in rca_rows.iterrows():
        label = _as_text(row.get("rca_label"), "RCA")
        st.markdown(
            f"""
            <div class="aq-card">
                <div class="aq-card-title">{label}</div>
                <div class="aq-muted">Schema: {_as_text(row.get('rca_schema'), '-')}</div>
                <div>{_as_text(row.get('rca_explanation'), 'No explanation recorded.')}</div>
            </div>
            """,
            unsafe_allow_html=True,
        )
        recommendations = _split_pipe(row.get("rca_recommendations"))
        if recommendations:
            st.markdown("**Suggested actions**")
            for recommendation in recommendations:
                st.markdown(f"- {recommendation}")
        notes = _as_text(row.get("rca_notes"))
        if notes:
            st.caption(notes)


def _selected_series_context(
    data: dict[str, pd.DataFrame],
    patient_series: pd.DataFrame,
    ct_id: str,
) -> tuple[pd.Series | None, pd.DataFrame, pd.DataFrame, list[Path]]:
    """Let the user pick one series and return its QC, RCA, and image context."""
    if patient_series.empty:
        return None, pd.DataFrame(), pd.DataFrame(), []

    st.markdown("<div class='aq-section-label'>Image and series selector</div>", unsafe_allow_html=True)
    ordered = patient_series.sort_values(["worst_status", "phase_name", "series_folder"], key=lambda column: column.map(lambda value: STATUS_ORDER.get(value, 99) if column.name == "worst_status" else str(value)))
    labels = [f"{row.phase_name or '-'} | {STATUS_LABELS.get(row.worst_status, row.worst_status)} | {row.series_folder}" for row in ordered.itertuples(index=False)]
    selected_label = st.selectbox("Series to review", labels, label_visibility="collapsed")
    selected = ordered.iloc[labels.index(selected_label)]
    series_folder = str(selected["series_folder"])

    quality_rows = data["image_quality"][
        data["image_quality"]["ct_id"].astype(str).eq(str(ct_id))
        & data["image_quality"]["series_folder"].astype(str).eq(series_folder)
    ].copy()
    rca_rows = data["rca"][
        data["rca"]["ct_id"].astype(str).eq(str(ct_id))
        & data["rca"]["series_folder"].astype(str).eq(series_folder)
    ].copy()
    image_paths = _image_paths_from_quality_rows(quality_rows)
    return selected, quality_rows, rca_rows, image_paths


def _render_selected_series_card(selected: pd.Series) -> None:
    """Show the selected series identity as a compact colored control card."""
    status = _as_text(selected.get("worst_status"), "missing")
    status_color = STATUS_COLORS.get(status, "#667085")
    series_folder = str(selected["series_folder"])
    actual_phase = _as_text(selected.get("actual_phase"), "n/a")
    predicted_phase = _as_text(selected.get("predicted_phase"))
    prediction_probability = selected.get("predicted_phase_probability")
    probability_label = f" ({_format_percentage(prediction_probability)})" if predicted_phase and pd.notna(prediction_probability) else ""
    prediction_match = selected.get("phase_prediction_matches")
    if predicted_phase:
        badge_label = _phase_match_label(prediction_match)
        badge_class = "aq-phase-match" if badge_label == "Match" else "aq-phase-mismatch"
        phase_prediction_html = f"{predicted_phase}{probability_label} <span class='aq-phase-badge {badge_class}'>{badge_label}</span>"
    else:
        phase_prediction_html = "No phase prediction found"
    st.markdown(
        f"""
        <div class="aq-card" style="border-left:5px solid {status_color};">
            <div class="aq-section-label">Selected series</div>
            <div class="aq-card-title">{series_folder}</div>
            <div class="aq-phase-comparison">
                <div class="aq-phase-line"><strong>Actual phase:</strong> {actual_phase}</div>
                <div class="aq-phase-line"><strong>Predicted phase:</strong> {phase_prediction_html}</div>
            </div>
            <span class="aq-chip">Procedure: {_as_text(selected.get('procedure_code'), '-')}</span>
            <span class="aq-chip">QC: {STATUS_LABELS.get(_as_text(selected.get('worst_status')), _as_text(selected.get('worst_status')))}</span>
            <span class="aq-chip">RCA: {_as_text(selected.get('rca_labels'), '-')}</span>
        </div>
        """,
        unsafe_allow_html=True,
    )


def _render_image_panel(selected: pd.Series | None, image_paths: list[Path]) -> None:
    """Render the segmentation/QC image beside the clinical text to reduce scrolling."""
    selected_name = _as_text(selected.get("series_folder"), "Selected series") if selected is not None else "Selected series"
    st.markdown(
        f"""
        <div class="aq-image-panel">
            <div class="aq-image-panel-title">
                <strong>Segmentation overlay</strong>
                <span class="aq-chip">Image review</span>
            </div>
            <div class="aq-image-caption">{selected_name}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )
    if image_paths:
        if len(image_paths) == 1:
            st.image(str(image_paths[0]), caption=image_paths[0].name, width="stretch")
        else:
            image_tabs = st.tabs([path.stem[:28] for path in image_paths])
            for tab, path in zip(image_tabs, image_paths, strict=False):
                with tab:
                    st.image(str(path), caption=path.name, width="stretch")
    else:
        st.info("No segmentation/QC overlay image was found for this series.")


def _render_series_detail(quality_rows: pd.DataFrame, rca_rows: pd.DataFrame) -> None:
    """Render QC and RCA details for the already selected series."""

    qc_col, rca_col = st.columns([1.05, 1.0])
    with qc_col:
        st.subheader("Image quality")
        _render_roi_cards(quality_rows)
    with rca_col:
        st.subheader("Probable causes")
        _render_rca_cards(rca_rows)

    with st.expander("Technical series details"):
        st.dataframe(quality_rows, hide_index=True, width="stretch")
        st.dataframe(rca_rows, hide_index=True, width="stretch")


def _render_extra_data(data: dict[str, pd.DataFrame], ct_id: str) -> None:
    """Keep raw source data available, but collapsed to preserve a minimal UI."""
    with st.expander("Source data and downloads"):
        injector_rows = data["injector_data"][data["injector_data"]["ct_id"].astype(str).eq(str(ct_id))]
        if not injector_rows.empty:
            st.markdown("**Injector data**")
            st.json(_read_json(injector_rows.iloc[0].get("data_json")))

        patient_payload = {
            "series": data["series"][data["series"]["ct_id"].astype(str).eq(str(ct_id))].to_dict("records"),
            "image_quality": data["image_quality"][data["image_quality"]["ct_id"].astype(str).eq(str(ct_id))].to_dict("records"),
            "rca": data["rca"][data["rca"]["ct_id"].astype(str).eq(str(ct_id))].to_dict("records"),
        }
        st.download_button(
            "Download patient JSON",
            data=json.dumps(patient_payload, indent=2, default=str),
            file_name=f"ai4quality_ct_{ct_id}.json",
            mime="application/json",
            width="stretch",
        )
        st.download_button(
            "Download SQLite database",
            data=DB_PATH.read_bytes(),
            file_name=DB_PATH.name,
            mime="application/vnd.sqlite3",
            width="stretch",
        )


def main() -> None:
    """Streamlit entry point for the final dashboard."""
    _configure_page()
    st.sidebar.title("AI4Quality")
    st.sidebar.caption("Final clinical dashboard")

    if "final_dashboard_refresh" not in st.session_state:
        st.session_state.final_dashboard_refresh = 0
    if "final_dashboard_force_rebuild" not in st.session_state:
        st.session_state.final_dashboard_force_rebuild = False
    if st.sidebar.button("Refresh database", width="stretch"):
        st.cache_data.clear()
        st.session_state.final_dashboard_refresh += 1
        st.session_state.final_dashboard_force_rebuild = True

    try:
        db_mtime_ns = DB_PATH.stat().st_mtime_ns if DB_PATH.exists() else 0
        data = _load_database(st.session_state.final_dashboard_refresh, st.session_state.final_dashboard_force_rebuild, db_mtime_ns)
        st.session_state.final_dashboard_force_rebuild = False
    except Exception as exc:
        st.error(f"Unable to load the consolidated database: {exc}")
        st.info("Run QC/RCA first, then run: python _04_Recommendations/generate_recommendations.py")
        return

    series_summary = _series_summary(data)
    patient_summary = _patient_summary(series_summary, data)
    if patient_summary.empty:
        st.warning("No analyzed cases are available. Run preprocessing, quality check, and RCA first.")
        return

    filtered_patients, filtered_series = _filter_data(series_summary, patient_summary)
    _metric_row(filtered_patients, filtered_series)
    selected_ct_id = _patient_selector(filtered_patients)
    if selected_ct_id is None:
        return

    patient_row = filtered_patients[filtered_patients["ct_id"].astype(str).eq(selected_ct_id)].iloc[0]
    patient_series = filtered_series[filtered_series["ct_id"].astype(str).eq(selected_ct_id)].copy()

    _render_patient_header(patient_row)
    _render_warnings(patient_row)

    narrative_col, image_col = st.columns([0.92, 1.08], gap="large")
    with image_col:
        selected_series, quality_rows, rca_rows, image_paths = _selected_series_context(data, patient_series, selected_ct_id)
        _render_image_panel(selected_series, image_paths)
    with narrative_col:
        _render_recommendation(data, selected_ct_id)
        st.subheader("Analyzed series")
        _render_series_table(patient_series)
        if selected_series is not None:
            _render_selected_series_card(selected_series)
            _render_series_detail(quality_rows, rca_rows)

    _render_extra_data(data, selected_ct_id)


if __name__ == "__main__":
    main()